name: Docker build and push template
on:
  schedule:
    # Rebuild every first day of the month at 6am.
    - cron: '0 6 1 * *'
  push:
    branches:
      - "main"
      - "test"
  workflow_dispatch:
jobs:
  build-application:
    uses: drupalforge/docker_publish_action/.github/workflows/docker-publish.yml@main
    with:
      dockerhub_username: ${{ vars.DOCKERHUB_USERNAME }}
    secrets:
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
      dp_ai_virtual_key: ${{ secrets.DP_AI_VIRTUAL_KEY }}
